/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2016-08-03 08:49:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class TestTraining_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/TestTraining.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/TestTraining.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-1.10.1.min.js\"></script>\r\n");
      out.write("<title>試験練習</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"loadTimeout()\">\r\n");
      out.write("<div id=\"screen\">\r\n");
      out.write("<form action=\"TestTrainingController\" method=\"post\" id=\"testTraining\" name=\"testTraining\">\r\n");
      out.write("<abbr title=\"戻る\"> <a id=\"modoru\" href=\"Menu.jsp\"><img\r\n");
      out.write("\t\t\t\t\tid=\"modoru\" src=\"css/picture/tan.png\"\r\n");
      out.write("\t\t\t\t\tonmouseover=\"src ='css/picture/tan2.png'\"\r\n");
      out.write("\t\t\t\t\tonmouseout=\"src ='css/picture/tan.png'\"></a>\r\n");
      out.write("\t\t\t</abbr>\r\n");
      out.write("\t\t\t<h3>試験練習</h3><br>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t<div id=\"levelList\">\r\n");
      out.write("\t<input type=\"button\" id=\"level1\" name=\"level1\" value=\"日本語検定試験1級\" onclick=\"chooseLv(this)\"><br>\r\n");
      out.write("\t<input type=\"button\" id=\"level2\" name=\"level2\" value=\"日本語検定試験2級\" onclick=\"chooseLv(this)\"><br>\r\n");
      out.write("\t<input type=\"button\" id=\"level3\" name=\"level3\" value=\"日本語検定試験3級\" onclick=\"chooseLv(this)\"><br>\r\n");
      out.write("\t<input type=\"button\" id=\"level4\" name=\"level4\" value=\"日本語検定試験4級\" onclick=\"chooseLv(this)\"><br>\r\n");
      out.write("\t<input type=\"button\" id=\"level5\" name=\"level5\" value=\"日本語検定試験5級\" onclick=\"chooseLv(this)\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"backdiv\" style=\"display: none;\">\r\n");
      out.write("\t<input type=\"button\" id=\"backbtn\" name=\"backbtn\" value=\"⇐\" onclick=\"backEvent()\"><br>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"testItem\" style=\"display: none;\">\r\n");
      out.write("\t<input type=\"hidden\" id=\"showTest\" name=\"showTest\" value=\"0\">\r\n");
      out.write("\t<input type=\"button\" id=\"vocabulary\" name=\"vocabulary\" value=\"言葉\" onclick=\"chooseItem(this.value)\"><br>\r\n");
      out.write("\t<input type=\"button\" id=\"kanji\" name=\"kanji\" value=\"漢字\" onclick=\"chooseItem(this.value)\"><br>\r\n");
      out.write("\t<input type=\"button\" id=\"grammar\" name=\"grammar\" value=\"文法\" onclick=\"chooseItem(this.value)\"><br>\r\n");
      out.write("\t<input type=\"button\" id=\"reading\" name=\"reading\" value=\"読解\" onclick=\"chooseItem(this.value)\"><br>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"backitemdiv\" style=\"display: none;\">\r\n");
      out.write("\t<label id=\"countTime\" style=\"font-size: 40px;\"><time>00:00:00</time></label>\r\n");
      out.write("\t<input type=\"button\" id=\"backyearbtn\" name=\"backyearbtn\" value=\"⇐\" onclick=\"backitemEvent()\"><br>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"testExam\" style=\"display: none;\">\r\n");
      out.write("\t<div id=\"testInfo\">\r\n");
      out.write("\t<textarea disabled=\"disabled\">質問：男の人と女の人が話しています。どの男の人について話していますか？\r\n");
      out.write("\t男：その男はどんな感じでした？\r\n");
      out.write("\t女：背広を着ていました。\r\n");
      out.write("\t男：めがねは？\r\n");
      out.write("\t女：めがねはかけていませんでした。\r\n");
      out.write("\t</textarea>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"questionInfo\">\r\n");
      out.write("\t<p>質問：どの男の人について話していますか？</p>\r\n");
      out.write("\t<table id=\"questionTable\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>1．セーターを着てまがねをかけてない。</td>\r\n");
      out.write("\t<td>3．制服を着てめがねをかけてない。</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>2．スーツを着てめがねをかけてない。</td>\r\n");
      out.write("\t<td>4．裸でめがねをかけていない。</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"btnDiv\">\r\n");
      out.write("\t<a href=\"#\" id=\"resultlink\" name=\"resultlink\">回答</a>\r\n");
      out.write("\t<label> : 3</label>\r\n");
      out.write("\t<a href=\"#\" id=\"detaillink\" name=\"detaillink\">詳細</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("<!-- \t<div id=\"audioDiv\">\r\n");
      out.write("\t<a href=\"#\" id=\"backlink\" name=\"backlink\">前へ</a>\r\n");
      out.write("\t<a href=\"#\" id=\"nextlink\" name=\"nextlink\">次へ</a>\r\n");
      out.write("\t</div> -->\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
