/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2016-06-14 08:50:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ResumeUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<form action=\"\">\r\n");
      out.write("<input type=\"button\" id=\"modoru\" name=\"modoru\" value=\"戻る\"><br>\r\n");
      out.write("<h3><b>経歴書更新</b></h3><br>\r\n");
      out.write("<label>社員ID</label><input type=\"text\" id=\"shainId\" name=\"shainId\"><br>\r\n");
      out.write("<label>自年月日</label><select></select><label>年</label><select></select><label>月</label><select></select><label>日</label><br>\r\n");
      out.write("<label>至年月日</label><select></select><label>年</label><select></select><label>月</label><select></select><label>日</label><br>\r\n");
      out.write("<label>業種</label><input type=\"text\" id=\"gyoushu\" name=\"gyoushu\"><br>\r\n");
      out.write("<label>業務名</label><textarea rows=\"\" cols=\"\"></textarea><br>\r\n");
      out.write("<label>職務内容</label><textarea rows=\"\" cols=\"\"></textarea><br>\r\n");
      out.write("<label>開発環境</label><br>\r\n");
      out.write("<label>OS</label><textarea rows=\"\" cols=\"\"></textarea>\r\n");
      out.write("<label>使用言語</label><textarea rows=\"\" cols=\"\"></textarea><br>\r\n");
      out.write("<label>DB</label><textarea rows=\"\" cols=\"\"></textarea>\r\n");
      out.write("<label>その他</label><textarea rows=\"\" cols=\"\"></textarea><br>\r\n");
      out.write("<input type=\"button\" id=\"addUpd\" name=\"addUpd\" value=\"登録\">\r\n");
      out.write("<input type=\"hidden\" id=\"actionId\" name=\"actionId\" value=\"");
      out.print(request.getAttribute("actionId"));
      out.write("\" >\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
